### ISSUE TITLE
converting plink format to fastStructure format

### ISSUE THREAD

**Issue by mjmontague** [StuntsPT/Structure_threader#24] opened 2016-09-20 16:04 UTC
I'd like to run your tool with a fastStructure wrapper, but my input files are plink formatted. Do you have a method for converting these to fastStructure format? Or does your tool currently work with plink formatted files?

**Comment by ODiogoSilva** [comment] 2016-09-20 16:21
As of now, input files for faststructure are assumed to be in 
.str format but I think plink input files can be easily supported in the next commits.

**Comment by StuntsPT** [comment] 2016-09-20 20:42
We can support this for fastStructure. Shouldn't be that difficult.
I'll just have to think what the best approach for entering the input would be.
Should the user just point to `file.bed` and the program will expect `file.fam` and `file.bim` to be present in the same path? Or is there a simpler way?
I don't really like the choice fastStructure made of asking the user to input a file without specifying an extension.
May we could have the user point to any of the 3 files and have fastStructure assume the other 2 are in the same path. That would avoid an extra configuration flag for the data type.

**Comment by StuntsPT** [comment] 2016-09-20 20:45
Also, BTW this is a duplicate of #20.

**Comment by StuntsPT** [comment] 2016-09-21 12:48
Fixed via commit 3318131.
Will make a new release with this feature once the docs are also up-to-date.

**Closed as completed by StuntsPT** 2016-09-21 12:48 UTC
Labels: duplicate, enhancement

**Comment by StuntsPT** [comment] 2016-09-21 14:06
New release v0.1.5 [here](https://github.com/StuntsPT/Structure_threader/releases/tag/v0.1.5), with this feature implemented.

**Comment by mjmontague** [comment] 2016-09-22 22:15
Thanks! We'll be using and citing your DOI in the near future

**Comment by StuntsPT** [comment] 2016-09-23 10:06
Glad to hear it. If you need any more support feel free to ask here.
Also, hopefully, we will soon have the software published (fingers crossed), but we'll keep our docs up-to-date on that too. Nevertheless, we really appreciate your support by citing at least the DOI (so, thanks!).
